build:
  needs: checkout
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'

    - name: Build with Maven
      # aponta para o pom na subpasta devcalc-api
      run: mvn -f devcalc-api/pom.xml clean install --batch-mode

test:
  needs: build
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4

    - name: Run tests
      # mesmo pom, mas rodar sรณ os testes
      run: mvn -f devcalc-api/pom.xml test --batch-mode
