name: CI

on:
  workflow_dispatch: {}      # <— permite rodar manualmente
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install --batch-mode

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: mvn test --batch-mode

  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Package JAR
        run: mvn package --batch-mode

  deploy:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Simulate Deploy
        run: echo "Deploy realizado com sucesso"


  lint:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkstyle
        uses: dbelyaev/action-checkstyle@v1.19.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: 'google_checks.xml'
          fail_on_error: true
          reporter: 'github-pr-check'
