name: CI DevCalc

on:
  workflow_dispatch:
    inputs:
      run_lint:
        description: 'Executar lint (Checkstyle)?'
        required: false
        default: 'true'
      run_tests:
        description: 'Executar testes?'
        required: false
        default: 'true'
  push:
    branches:
      - main
      - dev  # Adicionamos a branch dev
  pull_request:
    branches:
      - main
      - dev  # Adicionamos a branch dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install --batch-mode

  lint_and_test:
    needs: build
    uses: ./.github/workflows/lint-and-test.yml
    with:
      run_lint: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.run_lint || 'true' }}
      run_tests: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.run_tests || 'true' }}

  # --- NOVOS JOBS DE DEPLOY ---

  deploy-dev:
    name: Deploy para Desenvolvimento
    needs: lint_and_test
    # Só executa em push na branch 'dev'
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: dev # Conecta este job ao ambiente 'dev'
    steps:
      - name: Simulando deploy em DEV
        run: echo "🚀 Deploy para o ambiente de DEV realizado com sucesso!"

  deploy-prod:
    name: Deploy para Produção
    needs: lint_and_test
    # Só executa em push na branch 'main'
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: prod # Conecta ao ambiente 'prod' (com regra de aprovação)
    steps:
      - name: Simulando deploy em PROD
        run: echo "🔐 Deploy para o ambiente de PRODUÇÃO realizado com sucesso!"