name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - 'src/**'

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  build:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'
      - name: Build with Maven
        run: mvn clean install --batch-mode

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code again
        uses: actions/checkout@v4
      - name: Run tests
        run: mvn test --batch-mode
