name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - 'devcalc-api/src/**'     # opcional, se quiser disparar só em src do subdir

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  build:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'
      - name: Build with Maven
        working-directory: ./devcalc-api
        run: mvn clean install --batch-mode

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        working-directory: ./devcalc-api
        run: mvn test --batch-mode
