name: Lint and Test

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkstyle
        uses: dbelyaev/action-checkstyle@v1.19.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: 'google_checks.xml'
          reporter: 'github-pr-check'
          fail_level: 'warning'

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: mvn test --batch-mode
