name: Lint and Test

on:
  workflow_call:
    inputs:
      run_lint:
        description: 'Executar lint (Checkstyle)?'
        required: false
        type: boolean
        default: true
      run_tests:
        description: 'Executar testes?'
        required: false
        type: boolean
        default: true

jobs:
  lint:
    if: ${{ inputs.run_lint }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Checkstyle
        uses: dbelyaev/action-checkstyle@v1.19.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: 'google_checks.xml'
          reporter: 'github-pr-check'
          fail_level: 'warning'

  test:
    if: ${{ inputs.run_tests }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: mvn test --batch-mode
