name: Runner Auto-Hospedado

on:
  workflow_dispatch:

jobs:
  self_hosted_demo:
    runs-on: self-hosted
    steps:
      - name: Mostrar informações do sistema
        run: |
          echo "Usuário do GitHub: ${{ github.actor }}"
          systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
          java -version

      - name: Instalar 7-Zip sem precisar de admin
        run: |
          # URL apontando para a versão 23.01-portable do 7-Zip
          $zipUrl  = "https://www.7-zip.org/a/7z2301-x64.zip"
          $dest    = "$Env:RUNNER_TEMP\7zip.zip"
          Invoke-WebRequest -Uri $zipUrl -OutFile $dest

          Expand-Archive -Path $dest -DestinationPath "$Env:RUNNER_TEMP\7zip-portable"

          $exe = "$Env:RUNNER_TEMP\7zip-portable\7z.exe"
          & $exe --help
