name: Teste de Runner Auto-Hospedado

on:
  workflow_dispatch: # Permite iniciar manualmente pela aba Actions

jobs:
  test-self-hosted-runner:
    runs-on: self-hosted # Chave para usar seu runner local

    steps:
      - name: 1. Mostra o nome do computador (hostname)
        run: hostname

      - name: 2. Mostra a versão do Java instalado na máquina
        run: java -version

      - name: 3. Instala o Git usando Chocolatey (gerenciador de pacotes do Windows)
        run: choco install -y git