name: Teste de Variáveis e Secrets

on:
  workflow_dispatch:

jobs:
  display-vars-and-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Mostra as variáveis de ambiente
        run: |
          echo "Modo da Aplicação: ${{ vars.APP_MODE }}"
          echo "Email de Suporte: ${{ vars.SUPPORT_EMAIL }}"

      - name: 2. Simula o uso de um secret
        run: |
          echo "Simulando deploy com o token..."
          echo "Token utilizado: ${{ secrets.PROD_TOKEN }}"
